//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseTable
    {
        public int ExpenseID { get; set; }
        public string Detail { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public decimal Amount { get; set; }
    }
}
